### ISSUE TITLE
HTTPS Auto Redirection is Not Working 

### ISSUE THREAD

**Issue by adnanali-in** [expressjs/expressjs.com#1384] opened 2023-01-03 05:26 UTC
Its not Redirecting to HTTPS by Default

![Screenshot 2023-01-03 at 10 55 51 AM](https://user-images.githubusercontent.com/56250963/210304111-2761dc1b-34c0-4e14-8e7e-cfaf2ab7ea23.png)

![Screenshot 2023-01-03 at 10 54 15 AM](https://user-images.githubusercontent.com/56250963/210304037-ca84fb0b-d474-48d8-8ed5-f8d7b285f59b.png)

**Comment by dougwilson** [comment] 2023-01-03 05:28
Duplicate of #955

**Closed as completed by dougwilson** 2023-01-03 05:28 UTC
Labels: duplicate
