### ISSUE TITLE
locals.name = "hello" does not work

### ISSUE THREAD

**Issue by mbriot** [expressjs/expressjs.com#88] opened 2013-09-22 15:08 UTC
Because locals is a javascript function, we cannot used reserved names such as : 

```
name , apply , arguments , bind , call , caller , constructor...
```

This have to be documented in the  `app.locals` section.

This issue is linked to this one : https://github.com/visionmedia/express/issues/1514

**Comment by mbriot** [comment] 2013-09-26 13:51
@visionmedia  I send you a pull request for this issue. Thank you in advance for your feedback.

**Comment by jonathanong** [comment] 2013-12-10 22:50
dupe of #40

**Closed as completed by jonathanong** 2013-12-10 22:50 UTC
