### ISSUE TITLE
"Edit this page on GitHub" links are broken

### ISSUE THREAD

**Issue by Twipped** [expressjs/expressjs.com#265] opened 2014-11-03 23:06 UTC
On the bottom of http://expressjs.com/api.html there is a link to "Edit this page".  This link leads to a 404 error.

**Comment by hacksparrow** [comment] 2014-11-04 15:44
Thanks. Fixed in ec23199fefb136cd56894f0bd7198f906cca6a72. GitHub is taking some time to reflect the changes.

**Comment by crandmck** [comment] 2014-11-05 18:04
@hacksparrow Is this really fixed?  Seems like the site should have updated by now. The link still goes to https://github.com/strongloop/expressjs.com/blob/gh-pages/api.md, which does not exist.

**Comment by hacksparrow** [comment] 2014-11-06 04:08
Yes, it is fixed. This is a known issue on GitHub hosted sites. The syntax highlighter also took about a week to take effect. I am looking at ways to force it to serve the new file.

**Comment by dougwilson** [comment] 2014-11-06 04:10
One way to bust the cache is to add a use-less query string on the references to your static files and update the query string whenever the file gets updated.

**Comment by hacksparrow** [comment] 2014-11-06 04:14
Since there are multiple JavaScript files, it might start to look dirty with time. It might be better to fix the root cause - [CloudFare's rocket loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-).

**Comment by hacksparrow** [comment] 2014-11-06 06:51
They are using Local Storage for caching (implementation probably needs improvement), so appended a use-less query string to the main JS file to clear cache. Also disabled rocket loader to fix  #263.

**Closed as completed by hacksparrow** 2014-11-06 06:51 UTC
Labels: bug
