### ISSUE TITLE
Issue with using menu in API Reference

### ISSUE THREAD

**Issue by RyanJWilliams** [expressjs/expressjs.com#842] opened 2017-08-17 10:43 UTC
Hey all,

I'm using Safari 10.1.2 (12603.3.8) macOS, and when you select menu items in the API reference sidebar it goes to a completely different item. In Chrome macOS it's fine.

I've recorded a video of what's happening:

https://www.youtube.com/watch?v=toqj6PnziDE

I originally posted this in the Express issues tracker and some people on macOS there couldn't reproduce this, so not sure why it's happening in my case.

http://expressjs.com/en/api.html

**Comment by crandmck** [comment] 2017-08-17 18:15
I can't reproduce what you show in the vid myself, using Safari 10.1.2 (12603.3.8).  I do inconsistently see some squirrely behavior, though....sometimes the menu works fine, and sometimes it highlights the item below the one I click on, but displays the correct section.

**Comment by artze** [comment] 2019-06-12 04:23
I'm experiencing the same with Firefox 67.01.

Clicking on 'Request' menu item expands the 'Application' menu, for example.

**Comment by ryhinchey** [comment] 2020-04-08 20:01
> I can't reproduce what you show in the vid myself, using Safari 10.1.2 (12603.3.8). I do inconsistently see some squirrely behavior, though....sometimes the menu works fine, and sometimes it highlights the item below the one I click on, but displays the correct section.

using safari 13.0.5 on macos 10.15.3, I can replicate an issue similar to this.  The active menu item is not getting highlighted but the url does correctly change and the anchor link is correctly navigated to in the page.  When you refresh the page (something like `https://expressjs.com/en/4x/api.html#app.post.method`, it does highlight the correct menu item).

**Comment by bjohansebas** [comment] 2024-10-30 20:59
fixed by https://github.com/expressjs/expressjs.com/pull/1568

**Closed as completed by bjohansebas** 2024-10-30 20:59 UTC
Labels: bug, help wanted
