### ISSUE TITLE
Menu dropdown disappear when clicked twice

### ISSUE THREAD

**Issue by gfpacheco** [expressjs/expressjs.com#245] opened 2014-10-15 18:56 UTC
The menu HTML structure is wrong.
Dropit needs this to work:

```
  ul#navmenu.menu
    li#getting-started-menu
      a(href='/starter/installing.html', class=active == 'starter' ? 'active' : '') Getting started
      ul
        li
          a(href='/starter/installing.html') Installing
        li
          a(href='/starter/generator.html') Express generator
```

Instead of this:

```
  ul#navmenu
    li
      ul#getting-started-menu.menu
        li
          a(href='/starter/installing.html', class=active == 'starter' ? 'active' : '') Getting started
          ul
            li
              a(href='/starter/installing.html') Installing
            li
              a(href='/starter/generator.html') Express generator
```

But this change breaks the mobile version, I hope you guys have time to fix it.

**Comment by crandmck** [comment] 2014-10-15 22:30
@hacksparrow When you have a moment, please have a look.

**Comment by hacksparrow** [comment] 2014-10-16 12:51
The usage and behavior of Dropit has been intentionally altered to suit the requirements of the website, so it is advised to disregard how to it used. Let me know if there is a behavior problem.

You hover over the menu name - you get the menu.
You click on the menu name - you are taken to the default page of that section.

**Comment by gfpacheco** [comment] 2014-10-16 18:05
It's not how it behaves in my computer, maybe because it has touchscreen.

The menu does nothing when I hover.
When I click it open the dropdown.
But it I click on the menu name again it disappears together with the dropdown.

If you're ok with modifying the `dropit.js` I can suggest a fix.

**Comment by hacksparrow** [comment] 2014-10-16 18:11
See if you can accomplish it by altering `js/app.js`, instead. If it is not possible, go ahead and modify `dropit.js`. Please ensure it does not break something else.

**Comment by hacksparrow** [comment] 2014-10-19 07:06
Any updates @gfpacheco?

**Comment by crandmck** [comment] 2014-12-17 23:08
@gfpacheco Can you please advise?  If we don't hear back soon, I will close this issue.  AFAICT the menus work properly.

**Comment by dougwilson** [comment] 2014-12-17 23:20
Sounds like it's an issue with having touch on a desktop. I have a touchscreen laptop, so I'll see if I can confirm this issue later tonight.

**Comment by dougwilson** [comment] 2014-12-18 00:34
I'm seeing I guess this behavior when trying to use the touch screen on a Windows 8.1 laptop (in both IE and Firefox). It's not really possible to access anything in the drop down using the touch screen, since the only way to open the menu is to touch the menu item, which ends up just loading that page.

**Comment by crandmck** [comment] 2014-12-18 17:47
OK, thanks.  Will ask @hacksparrow to have a look when he's back.  The site should work on touchscreen or mobile device.

**Comment by dougwilson** [comment] 2014-12-18 18:33
>  The site should work on touchscreen or mobile device.

Yes, it does :) The menu also looks completely different on mobile, which is probably why it works with touch, unlike the desktop version.

**Comment by hacksparrow** [comment] 2015-10-16 08:57
Fixed it.

**Closed as completed by hacksparrow** 2015-10-16 08:57 UTC
