### ISSUE TITLE
Is there a reason behind no HTTPS/HSTS on expressjs.com?

### ISSUE THREAD

**Issue by bnb** [expressjs/expressjs.com#695] opened 2016-08-27 20:10 UTC
Ello!

I'm just curious if there was a reason that there's not an SSL/TLS certificate on the site. Since Express is such an important foundation in the Node community, it seems like being able to unquestionably verify that me accessing the unaltered site is important.

I definitely understand that there's no major secure content on the site (passwords, downloads, and so on), but there is definitely merit to having it for basic trust, as well as verification that all content on the site is accurate.

Has there been a previous discussion that led to a decision of no HTTPS? Would definitely love to take a look and understand the reasoning if there was!

**Comment by dougwilson** [comment] 2016-08-27 20:20
The Express.js website is currently offered over SSL for those who desire that: https://expressjs.com/ I don't have access to the CloudFlare account to manage any aspects of the site, though. @crandmck should know more about it.

**Comment by bnb** [comment] 2016-08-27 20:23
@dougwilson Ah, I'm a dope. Just typed "expressjs.com" in Chrome, without also trying HTTPS. That just goes to the  normal HTTP version, which is a highly annoying default. HSTS would 100% solve that, though.

**Comment by dougwilson** [comment] 2016-08-27 20:24
Yes, HSTS would, I just don't have access to do anything about it.

**Comment by dougwilson** [comment] 2016-08-27 20:30
There was a discussion on the CloudFlare account in a previous TC meeting, but I'm told it is not easy to transfer the expressjs.com account into the CF account for Node.js, so it is currently left outside of the Express.js TC's management. @jasnell may know more about if the account can be moved and then the Express.js TC would be able to manage the controls as it sees, like adding HTTP -> HTTPS redirects and the like. I don't want to commit to getting that in the account, as it is not clear to me where the current SSL certificate is coming from and adding that would cause it to break if that certificate were not renewed (I assume someone is paying for it?).

**Comment by bnb** [comment] 2016-08-27 20:30
@dougwilson Sorry - didn't mean to seem like I expected you (or anyone, really) to do that! Was just (rather obtusely, I think) stating the obvious. Apologies!

**Comment by bnb** [comment] 2016-08-27 20:37
@dougwilson If you're on CloudFlare, they offer a [free SSL cert](https://www.cloudflare.com/ssl/) via Comodo or GlobalSign - the site uses Comodo, so it might indeed be through CloudFlare.

**Comment by dougwilson** [comment] 2016-08-27 20:45
Ah, good to know, @bnb! So I think I answered all your questions from the issue.

> Is there a reason behind no HTTPS/HSTS on expressjs.com?

That is kind of a loaded question. We do offer HTTPS, but just do not set any HSTS header. Why no HSTS header is set has never been talked about in an Express.js TC meeting or in any conversation I have been a part of.

> Has there been a previous discussion that led to a decision of no HTTPS?

There was a long time in which the website was manage by a company and I don't believe there is any transparency in any decisions made during that time, so the Express.js TC is not able to answer the question, unfortunately. @crandmck was a part of that, so he may be able to speak to it. I think @rmg is another good person who can provide the answers you're looking for.

I can put this on the agenda to discuss in the next Express.js TC meeting, of course, though will need to solve the issue of how the Express.js TC can access & manage the CloudFlare account in an on-going basis first.

**Comment by rmg** [comment] 2016-08-28 00:19
@bnb yes, expressjs.com is currently being fronted by CloudFlare specifically for the SSL support. This has been the case since StrongLoop took ownership of the domain a couple years ago. :-)

I haven't checked whether CloudFlare has an option for setting HSTS, but I would be surprised if they didn't.

**Comment by bnb** [comment] 2016-08-28 17:17
Looks like they have an [article from 2015](https://blog.cloudflare.com/enforce-web-policy-with-hypertext-strict-transport-security-hsts/) saying you have to use their then-beta dashboard to enable directly through CloudFlare.

**Comment by bnb** [comment] 2016-08-28 17:18
And a newer post on their help site: https://support.cloudflare.com/hc/en-us/articles/204183088-Does-CloudFlare-offer-HSTS-HTTP-Strict-Transport-Security-

**Comment by crandmck** [comment] 2016-08-29 15:56
I confess I don't know anything about HSTS.  From what I can see, it helps prevent MITM attacks.  Should we be concerned about those (since the site doesn't perform any e-commerce or the like)?  If so, then is there any reason why we _wouldn't_ want to implement HSTS?  Apologies for my naïveté.  

@rmg What's your perspective re: pros/cons of HSTS?

IAC This decision would be up to the Express TC.

**Comment by rmg** [comment] 2016-09-06 17:31
My only concern is the site becoming inaccessible if SSL gets turned off for some reason, such as when transferring the domain or some similar event (because browsers will refuse to use http for the site until the HSTS header expires). That risk is pretty low, though, so I wouldn't consider it a good enough reason on its own to block this.

I won't be changing anything unless the TC asks for it, though.

**Comment by ryhinchey** [comment] 2020-04-08 19:46
it's been a few years since the last comment.  If the TC wanted to forward `http://expressjs.com` to `https://expressjs.com` as noted here https://github.com/expressjs/expressjs.com/issues/769, does anyone now know who could set that up?

**Comment by dougwilson** [comment] 2020-04-08 21:25
Yea, we have to get the CloudFlare account set to do with with the Node.js Foundation (or OpenJS now). I noticed you eventually found the thread on this 👍

**Comment by ryhinchey** [comment] 2020-04-08 22:18
Closing this issue as it’s a duplicate of https://github.com/expressjs/expressjs.com/issues/955

**Closed as completed** 2020-04-08 22:19 UTC
Labels: enhancement, help wanted
