### ISSUE TITLE
Video Tutorials for learning

### ISSUE THREAD

**Issue by packtpartner** [expressjs/expressjs.com#766] opened 2017-01-13 07:21 UTC
As the demand for video tutorials has increased in the IT industry, would it be appropriate to add video tutorials to http://expressjs.com/en/resources/books-blogs.html ?

**Comment by crandmck** [comment] 2017-01-13 19:32
Thanks for the suggestion, this is essentially a duplicate of #561.  I think it's a good idea. 
Can you suggest any specific video tutorials to which we should link?

I'll take this as a +1 for that issue, so I hope we can prioritize it soon.  You are also welcome to open a PR! :-)

**Closed as completed by crandmck** 2017-01-13 19:32 UTC

**Comment by packtpartner** [comment] 2017-01-16 07:36
Here are 3 Express video tutorials which could be added to the list.
[Learning Express Web Application Development (Video)](https://www.packtpub.com/web-development/learning-express-web-application-development-video)
[Mastering Express Web Application Development (Video)](https://www.packtpub.com/web-development/mastering-express-web-application-development-video)
[Build Complex Express Sites with Redis and Socket.io _Video)](https://www.packtpub.com/web-development/build-complex-express-sites-redis-and-socketio-video)

@crandmck would you be able to create a Video section and add these?

**Comment by crandmck** [comment] 2017-01-16 23:23
Yes, I'll do that asap.

**Comment by packtpartner** [comment] 2017-01-17 05:27
Thanks @crandmck . Could you tag me in the PR, so I can see it too

**Comment by crandmck** [comment] 2017-01-18 21:09
Sure, np.  
Unfortunately I'm slammed atm, but will do this just as soon as I can come up for air! :-)
