### ISSUE TITLE
Dark Mode/ Flash 

### ISSUE THREAD

**Issue by RaminHaghi** [expressjs/expressjs.com#1650] opened 2024-10-08 16:00 UTC
There's a flash on page load when user has dark mode set

We can inline the css and js to set up the page before it's rendered to the browser

Slowed down w/ connection throttling :

![flashing ui](https://github.com/user-attachments/assets/3a2b4dc0-70d7-4e70-a2f7-c48f0afec15c)

related https://github.com/expressjs/expressjs.com/pull/1490

**Comment by bjohansebas** [comment] 2024-10-15 01:47
Hi @RaminHaghi, thanks for reporting this. We already have a PR(#1621) to solve this issue, so I will close this issue since it's a duplicate of #1508.

**Closed as not planned by bjohansebas** 2024-10-15 01:47 UTC
Labels: bug
