### ISSUE TITLE
Hello World example broken, Runkit throws error on Safari

### ISSUE THREAD

**Issue by crcdng** [expressjs/expressjs.com#1038] opened 2019-04-24 11:15 UTC
This is the error message coming back after clicking on the green URL field.

```
{
  "error": "invalid_server",
  "message": "The requested document does not export an 'endpoint' function. Read more about endpoint: https://runkit.com/docs/endpoint"
}
```

**Comment by dougwilson** [comment] 2019-04-24 19:57
Are you still experiencing this issue? I just tried and it worked for me, so wasn't sure if it was a temporary issue or I need more instructions to reproduce it

**Comment by crcdng** [comment] 2019-04-25 14:44
I can reproduce the error on Safari  12.1 (MacOS Mojave). It seems Safari is more picky about iframes accessing each other. I found this in the console:

> Blocked a frame with origin "https://runkit.com" from accessing a frame with origin "https://expressjs.com". Protocols, domains, and ports must match.

The page works on Chrome.

**Comment by dougwilson** [comment] 2019-04-25 14:47
Thanks @i3games . I don't have access to Safari, so not sure what to do. cc: @tolmasky

**Comment by crcdng** [comment] 2019-04-25 14:56
I tried the express repo runkit on npm (https://npm.runkit.com/express) and it gives the same message about blocking the frame, but it works. Something with the runkit integration on expressjs.com?

**Comment by dougwilson** [comment] 2019-04-25 15:19
Yes, it could very well be. What can we change?

**Comment by tolmasky** [comment] 2019-04-25 15:26
Just tried this on Mojave 14.4.4 with Safari 12.1 (14607.1.40.1.4), and both the embed works as well as clicking on the link to actually try the endpoint.

Are you still seeing this error now? The error originally reported *could* have been a temporary hick-up with the site. The blocked iframe seems to be something just on npm.runkit.com (related to an unrelated new feature there) and I can not get it to reproduce on expressjs.com.

**Comment by tolmasky** [comment] 2019-04-25 15:39
FYI, the iframe blocking warnings appear to be fixed in the latest version of React: https://github.com/facebook/react/releases/tag/v16.8.6 (see the release notes). We'll update to that today to get rid of those (I'll check back here to confirm afterwards). Again though, that should be unrelated to the original bug report here.

**Comment by dougwilson** [comment] 2019-04-25 16:22
Thanks @tolmasky for checking! So it sounds like we can close this issue in this repo, as there doesn't seem to be any changes to make to the code here, right?

**Comment by tolmasky** [comment] 2019-04-25 16:24
Yeah, there definitely shouldn't be anything necessary on express' end. I just confirmed that 16.8.6 does in fact remove the blocked iframe warnings, and that is currently going through our CI now. So  that change should hopefully be live in a few minutes.

**Comment by dougwilson** [comment] 2019-04-25 16:25
Nice 👍

**Comment by tolmasky** [comment] 2019-04-25 16:45
Alright, it's live and I'm no longer getting the warnings. I can also load the endpoint just fine in Safari. I'd be happy to keep this open until the original user confirms but also understand if you want to close as not anything at fault with express.

**Comment by dougwilson** [comment] 2019-04-25 17:30
Nice :+1:

**Closed as completed by dougwilson** 2019-04-25 17:30 UTC

**Comment by crcdng** [comment] 2019-04-25 20:09
Confirming it works now. Thanks for the update.
